name: Server插件编译

on:
  workflow_dispatch:

jobs:
  build-server:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Clone仓库
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 0
      
      - name: Clone Server仓库
        run: |
          git submodule update --init Server

      - name: 生成Server发布版本号
        id: version
        shell: bash
        run: |
          new_tag="server-v1.0.0"
          latest=$(gh release list --json tagName --jq '.[0].tagName' 2>/dev/null || true)
          if [ -n "$latest" ] && [[ $latest =~ server-v([0-9]+)\.([0-9]+)\.([0-9]+) ]]; then
            major=${BASH_REMATCH[1]}
            minor=${BASH_REMATCH[2]}
            patch=${BASH_REMATCH[3]}
            new_patch=$((patch + 1))
            new_tag="server-v$major.$minor.$new_patch"
          fi
          echo "tag=$new_tag" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 安装依赖
      - name: 安装32位CMake编译环境
        run: |
          sudo apt update
          sudo apt install -y gcc gcc-multilib g++-multilib wget
          sudo -i << 'EOF'
          cd /usr/local
          wget https://github.com/Kitware/CMake/releases/download/v3.22.6/cmake-3.22.6-linux-x86_64.tar.gz
          tar -zxvf cmake-3.22.6-linux-x86_64.tar.gz
          ln -sf /usr/local/cmake-3.22.6-linux-x86_64/bin/cmake /usr/bin/cmake
          EOF
          cmake --version

      # 编译 monitor
      - name: 编译libfd_monitor.so
        run: |
          cd Server/monitor
          sed -i '1s/^.//' CMakeLists.txt
          sed -i 's|set(CMAKE_LIBRARY_OUTPUT_DIRECTORY|#set(CMAKE_LIBRARY_OUTPUT_DIRECTORY|g' CMakeLists.txt
          rm -rf build && mkdir build && cd build
          cmake .. -DCMAKE_C_FLAGS="-m32" -DCMAKE_CXX_FLAGS="-m32"
          make -j4

      # 编译 server
      - name: 编译libfd.so
        run: |
          cd Server/server
          sed -i '1s/^.//' CMakeLists.txt
          sed -i 's|set(CMAKE_LIBRARY_OUTPUT_DIRECTORY|#set(CMAKE_LIBRARY_OUTPUT_DIRECTORY|g' CMakeLists.txt
          rm -rf build && mkdir build && cd build
          cmake .. -DCMAKE_C_FLAGS="-m32" -DCMAKE_CXX_FLAGS="-m32"
          make -j4

      # 整理文件
      - name: 整理编译插件
        run: |
          mkdir -p output
          cp Server/monitor/build/libfd_monitor.so output/
          cp Server/server/build/libfd.so output/

      # 上传到 Releases
      - name: 发布到 GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          name: "${{ steps.version.outputs.tag }}"
          body: "服务端插件\n libfd_monitor.so\n libfd.so"
          files: output/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}